### ISSUE TITLE
Add support for Embeds / oEmbeds

### ISSUE THREAD

**Issue by waltir** [xuopled/gatsby-source-google-docs#18]
Adding oEmbed / Embed support would be very helpful. Every attempt I've made to add a codepen embed to my test post has, unfortunately, failed. So have all of my oEmbed and Embed tests from the popular social share sites. Is there a workaround for this that I'm somehow overlooking or is it not currently possible  using `gatsby-source-google-docs`? 

So far this plugin has been pretty amazing, however, not having the ability to embed social content in a blog post might be a blocker for me. 

Thanks in advance for your time. I really appreciate it!

**Comment by xuopled** [comment]
Unfortunately, `gatsby-source-google-docs` can't do what `google-docs` can't do. 

The solution could be to write a `gatsby-transformer-remark` plugin to fetch oEmbed content. If you do this, please share your solution with us 🙂

**Comment by waltir** [comment]
@xuopled Thanks for following up. I ended up having amazing success with https://www.gatsbyjs.org/packages/@raae/gatsby-remark-oembed/?=remark%20oembed.

**Comment by xuopled** [comment]
Good to know. Thank you for your feedback
