### ISSUE TITLE
Adding a slug is unexpected behavior

### ISSUE THREAD

**Issue by KyleAMathews** [xuopled/gatsby-source-google-docs#19]
I'm working on a site with this plugin and in a previous version I'd added a custom slug. I upgraded and now Gatsby is throwing an error as this plugin is setting the field already.

This is unexpected behavior as Source plugins should only concern themselves with sourcing data. Not with site-specific needs like what the slug should be. There's lots of potential ways to create slugs.

Would you be ok removing that code?

**Comment by xuopled** [comment]
Oh sorry about that.

Maybe it's possible to get the original node internal type `GoogleDocs` and do somethiong like `if (
    node.internal.type === "MarkdownRemark" and originalType === "GoogleDocs" and !node.fields.slug`.

What do you think?

**Comment by xuopled** [comment]
You are right, it was an unexpected behavior.
I just removed it in `v1.6.1`

**Comment by KyleAMathews** [comment]
Thanks!

Yeah
