### ISSUE TITLE
What to do with the token file when publishing to Netlify or similar?

### ISSUE THREAD

**Issue by eriklofblad** [xuopled/gatsby-source-google-docs#23]
Great work with this plugin!
However, I wonder how to get it working when publishing to something like Netlify since I don't want to commit the "google-docs-token.json" to source control and it's not possible to input the code in the build output?
Is it possible to add the token to env variables and read it from there instead of from the json-file?

**Comment by xuopled** [comment]
You are right, we have to refactor this part to make it possible to read it from env variable. But for now it's not possible. 

If someone have any idea or want to help me about this, I would be grateful :)

**Comment by eriklofblad** [comment]
Could something like this in auth.js be a solution?

```
async function getToken({access_type, client, scope, token_path}) {
  if(process.env.GDOCS_TOKEN){
    const token = JSON.parse(process.env.GDOCS_TOKEN)
    return token
  }else if (fs.existsSync(token_path)) {
    const token = JSON.parse(fs.readFileSync(token_path, "utf-8"))
    return token
  } else {
    const token = await getNewToken({access_type, client, scope})
    fs.writeFileSync(token_path, JSON.stringify(token))
    return token
  }
}
```

Or is it better to add a config option to pass the env variable?

**Comment by xuopled** [comment]
@eriklofblad it's better to add a config to pass the env variable. But a first version with the code above could be a good move

**Comment by justinsunho** [comment]
@xuopled @eriklofblad I'm currently working on this. Will likely send a PR soon If that's ok with you guys.

**Comment by eriklofblad** [comment]
@justinsunho sounds awesome if your're already working on it! Looking forward to it!

**Comment by xuopled** [comment]
`v1.10.0` released
