### ISSUE TITLE
"Authorize this app by visiting this url" is empty

### ISSUE THREAD

**Issue by shalanah** [xuopled/gatsby-source-google-docs#27]
Looks like this when I run `gatsby develop`. I'm missing a `url` to click on.
```
Authorize this app by visiting this url:
⠙ source and transform nodes
Enter the code from that page here: 
```

**Comment by shalanah** [comment]
I went through https://developers.google.com/drive/api/v3/quickstart/nodejs set up to generate a token.json and then pointed to that in `token_path`

**Comment by jhthompson** [comment]
Running into the same issue - did you ever find a way to make the URL appear in the default setup?

**Comment by justinsunho** [comment]
@jhthompson for me, it's usually a matter of my terminal's settings. The url is often too long for it to display in my window. I just make the window bigger or the text smaller and the url displays correctly. Hopefully your issue is as simple as mine

**Comment by jhthompson** [comment]
That was it, thank you! Never seen that before.

**Comment by raufsamestone** [comment]
> I went through https://developers.google.com/drive/api/v3/quickstart/nodejs set up to generate a token.json and then pointed to that in `token_path`

Hey @shalanah ,

Did you configured in .json or Domain verification settings in Google API?

I created a json file, pointed the `token_path`, but I get either empty URL or  `No access, refresh token or API key is set` 

My `gatsby-config.js `like that:

```
  {
      resolve: "gatsby-source-google-docs",
      options: {
          // Mandatory
          // --------
          foldersIds: ["1zXPP......HisoelF8DO"], // folders Ids can be found in Google Drive URLs
          config: {
            api_key: "AIzaS.......WbZQ",
            client_id: "3032.......7dd23.apps.googleusercontent.com",
            client_secret: "NKBEh........7jPAI",
              scope: [
                  "https://www.googleapis.com/auth/documents.readonly", // GoogleDocs API read access
                  "https://www.googleapis.com/auth/drive.metadata.readonly", // GoogleDrive API read access
              ],
              token_path: "google-docs-token.json",
          },
          // Optional
          // --------
          fields: ["createdTime"], // https://developers.google.com/drive/api/v3/reference/files#resource
          fieldsMapper: {createdTime: "date", name: "title"}, // To rename fields
      },
```

**PS:** The json file is in root
