### ISSUE TITLE
`gatsby-node.js` can not config plugins now

### ISSUE THREAD

**Issue by vitostan** [xuopled/gatsby-source-google-docs#32]
Hi xuopled,

It seems that we can't config plugins in `gatsby-node.js` but have to do it in `gatsby-config.js`. But in your doc `Usage` section, it is still 

> In your `gatsby-node.js` file, configure the `gatsby-source-google-docs` and the ... plugins

Should be updated I guess?

And another issue happened could be derived from that, which is the GraghQL web console could not find the `.png` image that I put in my google drive even if it could query the google doc in it. So does anybody else face the same issue?

**Comment by xuopled** [comment]
Hi, you are right, the configuration should be done in 'gatsby-config.js`

**Comment by xuopled** [comment]
> And another issue happened could be derived from that, which is the GraghQL web console could not find the .png image that I put in my google drive even if it could query the google doc in it. So does anybody else face the same issue?

`gatsby-source-google-docs` is usefull only to query google docs, not images. If you need some feature, please open a specific issue. I'm also open to PR of course :)

**Comment by vitostan** [comment]
OK, thanks for replying, I got it.
