### ISSUE TITLE
error GraphQL Error Unknown field `markdownRemark` on type `Query`

### ISSUE THREAD

**Issue by adebnar** [xuopled/gatsby-source-google-docs#4]
When I follow basic plug-in documentation I receive the following messages
Run ``npm run develop``

> success open and validate gatsby-config — 0.008 s
> success load plugins — 0.516 s
> success onPreInit — 3.545 s
> success delete html and css files from previous builds — 0.007 s
> success initialize cache — 0.007 s
> success copy gatsby files — 0.646 s
> success onPreBootstrap — 0.005 s
> success source and transform nodes — 0.030 s
> success building schema — 1.336 s
> success createPages — 0.000 s
> success createPagesStatefully — 0.086 s
> success onPreExtractQueries — 0.002 s
> success update schema — 0.078 s
> GraphQL Error Unknown field `markdownRemark` on type `Query` 
> 
>   file: /home/adebnar/doc-blog/src/templates/post.js
> 
>    1 |
>    2 |     query BlogPostBySlug($slug: String!) {
> >  3 |         post: markdownRemark(fields: {slug: {eq: $slug}}) {
>      |               ^
>    4 |             html
>    5 |             frontmatter {
>    6 |                 name
>    7 |                 createdTime(formatString: "DD MMMM YYYY", locale: "fr")
>    8 |             }
>    9 |         }
>   10 |     }
>   11 |
> 
> success extract queries from components — 0.423 s
> ⠁ (node:487) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
> success run graphql queries — 0.040 s — 1/1 27.43 queries/second

**Comment by xuopled** [comment]
Did you add the `gatsby-transformer-remark` plugin ?
```
{
            resolve: "gatsby-transformer-remark",
            options: {
                plugins: [],
            },
        },
```

**Comment by adebnar** [comment]
Looks like I missed that. I'll give that a try.

Thanks

**Comment by xuopled** [comment]
You can do without this plugin but you will request `googleDocs` type and not `markdownRemark`.

**Comment by waltir** [comment]
I'm continually encountering the same behavior even after following this step. I've logged the title of my sheet several times to the terminal so I know the data is there and that its not a google api issue. I figured maybe by asking here it could help someone else. Perhaps I'm overlooking something obvious. 

Error: "GraphQLError: Cannot query field "fields" on type "MarkdownRemark"."

gatsby-config.js
`module.exports = {
        plugins: [
        'gatsby-plugin-sass',
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                name: 'src',
                path: `${__dirname}/src/`
            }
        },
        {
            resolve: "gatsby-source-google-docs",
            options: {
                foldersIds: ["xxx"], 
                config: {
                    api_key: "xxx",
                    client_id: "xxx",
                    client_secret: "xxx",
                    access_type: "offline",
                    redirect_uris: [
                        "urn:ietf:wg:oauth:2.0:oob",
                        "http://localhost",
                    ],
                    scope: [
                        "https://www.googleapis.com/auth/documents.readonly", // GoogleDocs API read access
                        "https://www.googleapis.com/auth/drive.metadata.readonly", // GoogleDrive API read access
                    ],
                    token_path: "google-docs-token.json",
                },
                fields: ["createdTime"], // https://developers.google.com/drive/api/v3/reference/files#resource
                fieldsMapper: {createdTime: "date", name: "title"}, // To rename fields
            },
        },
        {
            resolve: "gatsby-transformer-remark",
            options: {
                plugins: [],
            },
        },
    ]
}`


./src/templates/post.js
`import React from "react"

const PostTemplate = ({data: {post}}) => (
    <p>
        <h1>{post.frontmatter.name}</h1>
        <p>{post.frontmatter.createdTime}</p>
        <div dangerouslySetInnerHTML={{__html: post.html}} />
    </p>
)

export default PostTemplate

export const pageQuery = graphql`
    query BlogPostBySlug($slug: String!) {
        post: markdownRemark(fields: {slug: {eq: $slug}}) {
            html
            frontmatter {
                name
                createdTime(formatString: "DD MMMM YYYY", locale: "fr")
            }
        }
    }
``


gatsby-node.js
`const _kebabCase = require("lodash/kebabCase")

exports.onCreateNode = ({node, actions}) => {
    if (node.internal.type === `MarkdownRemark` && node.frontmatter.title) {
        actions.createNodeField({
            name: `slug`,
            node,
            value: `/${_kebabCase(node.frontmatter.title)}`,
        })
    }
}`

**Comment by xuopled** [comment]
@waltir I think there are multiple issues in your code.

First, your post template is wrong. You request name and createdTime but they don't exist anymore because you use `fieldsMapper: {createdTime: "date", name: "title"}`. So tried to replace them by date and title
