### ISSUE TITLE
fieldsMapper makes fields undefined

### ISSUE THREAD

**Issue by tomasforsman** [xuopled/gatsby-source-google-docs#5]
I am using google docs and md files as sources. The problem I have is that when I try to use fieldsMapper to change name of title to name it stops creating the slug and says fields is undefined. If I don't try to use fieldsMapper it creates the slug fields for both md files (using gatsby source filesystem) and google docs. Where have I gone wrong?

**Comment by tomasforsman** [comment]
`    {
      resolve: "gatsby-source-google-docs",
      options: {
          // Mandatory
          // --------
          foldersIds: [" ---- ", " ----- "], // folders Ids can be found in Google Drive URLs
          config: {
              api_key: " ---- ",
              client_id: "----.apps.googleusercontent.com",
              client_secret: " ---- ",
              // Optional
              // --------
               access_type: "offline",
              redirect_uris: [
                  "urn:ietf:wg:oauth:2.0:oob",
                  "http://localhost:9000",
              ],
              scope: [
                  "https://www.googleapis.com/auth/documents.readonly", // GoogleDocs API read access
                  "https://www.googleapis.com/auth/drive.metadata.readonly", // GoogleDrive API read access
              ],
              token_path: "google-docs-token.json", 
          },
          // Optional
          // --------
            fields: ["createdTime"], // https://developers.google.com/drive/api/v3/reference/files#resource
            fieldsMapper: {createdTime: "date", name: "title"}, // To rename fields 
      },
    },
`

and


`const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)
const _kebabCase = require("lodash/kebabCase")

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions


  if (node.internal.type === `MarkdownRemark` && node.frontmatter.name){
    createNodeField({
      node,
      name: `slug`,
      value: `/${_kebabCase(node.frontmatter.name)}`,
    })
  }

  if (node.internal.type === `MarkdownRemark` && node.fileAbsolutePath) {
    const slug = createFilePath({ node, getNode, basePath: `pages` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
  

}

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  const blogPostTemplate = path.resolve(`./src/templates/blog-post.js`)
  const googlePostTemplate = path.resolve(`./src/templates/google-post.js`)
  return graphql(`
    {
     local: allMarkdownRemark(
        filter: {parent: {internal: {type: {eq: "File"}}}}
      ){
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    google: allMarkdownRemark(
      filter: {parent: {internal: {type: {eq: "GoogleDocs"}}}}
    ){
      edges {
        node {
          fields {
            slug
          }
        }
      }
    }

    }
  `).then(result => {

    if (result.errors) {
      return Promise.reject(result.errors)
    }

    const local = result.data.local.edges
    const google = result.data.google.edges

    local.forEach(({ node }) => {
        createPage({
          path: node.fields.slug,
            component: path.resolve(`./src/templates/blog-post.js`),
          context: {
            // Data passed to context is available
            // in page queries as GraphQL variables.
            slug: node.fields.slug,
          },
        })
    })

    google.forEach(({ node }) => {
      createPage({
        path: node.fields.slug,
          component: path.resolve(`./src/templates/blog-post.js`),
        context: {
          slug: node.fields.slug,
        },
      })
  })
  })
}
`

**Comment by tomasforsman** [comment]
config
https://gist.github.com/tomasforsman/2793dd8b395f34184893d44a50de2514

node
https://gist.github.com/tomasforsman/45c00a43672440b085b2b2a34e127f7a

**Comment by xuopled** [comment]
if you use `fieldsMapper` to rename `name` to `title`, you have to replace the slug generation by:

```
if (node.internal.type === `MarkdownRemark` && node.frontmatter.title){
    createNodeField({
      node,
      name: `slug`,
      value: `/${_kebabCase(node.frontmatter.title)}`,
    })
```

**Comment by xuopled** [comment]
@tomasforsman Do you still have a problem with this ?

**Comment by tomasforsman** [comment]
No, big thanks for your help. It was, of course, an obvious mistake.

Keep on being awesome and have a great day.

**Comment by xuopled** [comment]
Thank you very much for your feedback 😃Have a great day too
