### ISSUE TITLE
Error: source-google-docs: No access, refresh token or API key is set.

### ISSUE THREAD

**Issue by odm275** [xuopled/gatsby-source-google-docs#6]
success open and validate gatsby-configs — 0.010 s
success load plugins — 0.223 s
success onPreInit — 1.554 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache — 0.016 s
success copy gatsby files — 0.069 s
success onPreBootstrap — 0.010 s
error Plugin gatsby-source-google-docs returned an error

  Error: source-google-docs: No access, refresh token or API key is set.
  
  - gatsby-node.js:341 Object.exports.sourceNodes
    [poetic-docs]/[gatsby-source-google-docs]/gatsby-node.js:341:10
  

warning The gatsby-source-google-docs plugin has generated no Gatsby nodes. Do you need it?

Do I need to change some config in my google developer console? I pretty much copied the gatsby-config and gatsby-node files from the tutorial and replaced with my own keys.

**Comment by xuopled** [comment]
Do you have the `google-docs-token.json` at the root of your repo? It should be generated the first launch

**Comment by odm275** [comment]
Hey,
I do have google-docs-token.json at the root. I removed it.
Gatsby Develop, got a link to authorize the app, and now I'm getting Error: redirect_uri_mismatch
What did I set up wrong?

**Comment by xuopled** [comment]
Could you share your config in `gatsby-config.js` or a repo to reproduce ?

**Comment by odm275** [comment]
https://github.com/odm275/docs/blob/master/gatsby-config.js

Sure thing!

**Comment by xuopled** [comment]
You forgot `const path = require("path")` at the top of your `gatsby-node.js`.

Otherwise, I have no error (Just comment the Image component).

It seems like one of the following is empty in your code:
``
`
foldersIds: [process.env.GOOGLE_FOLDER_ID], // folders Ids can be found in Google Drive URLs
process.env.GOOGLE_API_KEY,
process.env.GOOGLE_CLIENT_ID,
process.env.GOOGLE_CLIENT_SECRET,
```

**Comment by odm275** [comment]
I added const path = require("path") and commented out the Image Component on the index page. I consoled logged my environment variables and they're coming in before any other process happens. All seems good there. The command line spits out a link to authorize an app, I go that link and it still displays: 
Error: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauth

In the request details, I see the client_id coming in fine.

Any thoughts?

**Comment by odm275** [comment]
Hey, I solved it! I was getting mixed up two different set of keys. I was putting the client/secret from my google docs api OAuth 2.0 client IDs in the gatsby config, but the ones from google drive drive api were the right ones.

**Comment by xuopled** [comment]
Good to hear :)
