### ISSUE TITLE
Also experiencing error first time running yarn dev

### ISSUE THREAD

**Issue by jamessimone** [xuopled/gatsby-source-google-docs#7]
Hi there,

I followed the steps to turn on the Google Docs / Drive API, however, on running yarn dev I still get stuck on this step - when I open the link generated below, I select the google account associated with the client id that I've created, and then I am immediately "redirected" to a page with a url like such:

http://localhost/?code=xxxxxxxxxxxxxxxx_THIS_IS_A_RIDICULOUSLY_LONG_AUTO_GENERATED_AUTH_STRING___xxxxxx&scope=https://www.googleapis.com/auth/documents.readonly%20https://www.googleapis.com/auth/drive.metadata.readonly

However, I cannot *paste* the code into my terminal, which is sitting idle with the below text:

`$ yarn dev`
`yarn run v1.12.3`
`$ gatsby develop`
`success open and validate gatsby-configs — 0.029 s`
`success load plugins — 0.699 s`
`success onPreInit — 2.893 s`
`success initialize cache — 0.040 s`
`success copy gatsby files — 0.296 s`
`success onPreBootstrap — 0.045 s`
⠁ Authorize this app by visiting this url: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocuments.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata.readonly&response_type=code&client_id=xxxxx_MY_CLIENT_ID_xxxxx&redirect_uri=http%3A%2F%2Flocalhost
`Enter the code from that page here:`

There is no way for me to enter the code. The terminal is not in any kind of editable mode, and I have tried bash / powershell  / command line without being able to proceed. I am sure that there is something very easy that I am missing here. Any assistance you can offer would be much appreciated.

**Comment by jamessimone** [comment]
Aha, after digging through the source code I realized that the editors were just not displaying the pasted text. Sorry about this!

**Comment by xuopled** [comment]
No problem. I'm glad to see there is no problem :)

**Comment by jamessimone** [comment]
Yeah it's working really well! Thanks for your work :)

**Comment by xuopled** [comment]
You are welcome 😃
